/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obj_finall_project;

import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */


public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(745, 920));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 64));
        jLabel2.setFont(new java.awt.Font("Georgia", 2, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BookStore");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setBackground(new java.awt.Color(78, 22, 78));
        jLabel1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("|   Categories   |");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("|   Cart   |");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jList1.setBackground(new java.awt.Color(102, 0, 0));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jList1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jList2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jList2.setFocusTraversalPolicyProvider(true);
        jList2.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(jList2);

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SELECT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 0, 0));
        jButton3.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADD TO CART");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Remove ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jList3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jList3.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jScrollPane3.setViewportView(jList3);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Price : ");
        jLabel5.setToolTipText("");

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Confirm Cart");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated
    DefaultListModel model = new DefaultListModel();
    Calculate c=new Calculate();
    
    public double Total;
    ArrayList<String> list=new ArrayList<String>();
    
    ArtDesign art=new ArtDesign();
    Literature ltr=new Literature();
    Philosophy phl=new Philosophy();
    ResearchHistory res=new ResearchHistory();
    Science scn=new Science();
        
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jList1.clearSelection();
        DefaultListModel model = new DefaultListModel();
        jList1.setModel(model);
         
        model.addElement("Art-Design");
        model.addElement("Literature");
        model.addElement("Philosophy");
        model.addElement("Research-History");
        model.addElement("Science");
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        jList2.clearSelection();
        DefaultListModel model = new DefaultListModel();
        jList2.setModel(model);
        
        if(jList1.getSelectedValue().equals("Art-Design"))
        {
            model.addElement("Antigone");
            model.addElement("Elektra");
            model.addElement("Hamlet");
            model.addElement("Kral Oidipus");
            model.addElement("Monet");
            model.addElement("Raffaello");
            model.addElement("Romeo ve Juliet");
            model.addElement("Velázquez");
            model.addElement("Venedik Taciri");
        }
        if(jList1.getSelectedValue().equals("Literature"))
        {
            model.addElement("Aforizmalar");
            model.addElement("Dava");
            model.addElement("Dönüşüm");
            model.addElement("Huzursuzluk");
            model.addElement("Karamazov Kardeşler");
            model.addElement("Kardeşimin Hikayesi");
            model.addElement("Serenad");
            model.addElement("Suç ve Ceza");
            model.addElement("Yeraltından Notlar");
        }
        if(jList1.getSelectedValue().equals("Philosophy"))
        {
            model.addElement("Böyle Buyurdu Zerdüşt");
            model.addElement("Devlet");
            model.addElement("Düşüş");
            model.addElement("İyinin ve Kötünün Ötesinde");
            model.addElement("Putların Alacakaranlığı");
            model.addElement("Sofist");
            model.addElement("Sokrates'in Savunması");
            model.addElement("Veba");
            model.addElement("Yabancı");
        }
        if(jList1.getSelectedValue().equals("Research-History"))
        {
            model.addElement("Devlet-i Aliyye-Osmanlı İmparatorluğu");
            model.addElement("Fatih Sultan Mehemmed Han");
            model.addElement("Gazi Mustafa Kemal Atatürk");
            model.addElement("Hayvanlardan Tanrılara Sapiens");
            model.addElement("Homo Deus : Yarının Kısa Bir Tarihi");
            model.addElement("İstanbul'dan Sayfalar");
            model.addElement("Rönesans Avrupası");
            model.addElement("Türklerin Altın Çağı");
            model.addElement("21. Yüzyıl için 21 Ders");
        }
        if(jList1.getSelectedValue().equals("Science"))
        {
            model.addElement("Her Şeyin Anlamı");
            model.addElement("Feynmen Fizik Dersleri");
            model.addElement("Altı Zor Parça");
            model.addElement("Zamanın Kısa Tarihi");
            model.addElement("Karadelikler");
            model.addElement("Büyük Sorulara Kısa Yanıtlar");
            model.addElement("Hiper Uzay");
            model.addElement("Paralel Dünyalar");
            model.addElement("İnsanlığın Geleceği");
        }
        if(jList1.getSelectedValue().equals(null)){
            
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jList2.getSelectedValue().equals("Suç ve Ceza"))
        {
            ltr.SucVeCeza();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Karamazov Kardeşler"))
        {
            ltr.KaramozovKardesler();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Yeraltından Notlar"))
        {
            ltr.YerAltindanNotlar();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Dönüşüm"))
        {
            ltr.Donusum();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Aforizmalar"))
        {
            ltr.Aforizmalar();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        
        if(jList2.getSelectedValue().equals("Dava"))
        {
            ltr.Dava();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Serenad"))
        {
            ltr.Serenad();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Huzursuzluk"))
        {
            ltr.Huzursuzluk();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Kardeşimin Hikayesi"))
        {
            ltr.KardesiminHikayesi();
            JOptionPane.showMessageDialog(rootPane,"Name : "+ltr.bookName+"\n"+"Writer : "+ltr.writer+"\n"+
            "Type : "+ltr.type+"\n"+"Page Number : "+ltr.pageNumber+"\n"+"Price : "+ltr.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Venedik Taciri"))
        {
            art.VenedikTaciri();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Romeo ve Juliet"))
        {
            art.RomeoJuliet();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Hamlet"))
        {
            art.Hamlet();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Velázquez"))
        {
            art.Velazquez();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Raffaello"))
        {
            art.Raffaello();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Monet"))
        {
            art.Monet();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Antigone"))
        {
            art.Antigone();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Kral Oidipus"))
        {
            art.Oidipus();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Elektra"))
        {
            art.Elektra();
            JOptionPane.showMessageDialog(rootPane,"Name : "+art.bookName+"\n"+"Writer : "+art.writer+"\n"+
            "Type : "+art.type+"\n"+"Page Number : "+art.pageNumber+"\n"+"Price : "+art.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Devlet"))
        {
            phl.Devlet();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Sokrates'in Savunması"))
        {
            phl.Sokrates();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Sofist"))
        {
            phl.Sofist();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Yabancı"))
        {
            phl.Yabancı();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Veba"))
        {
            phl.Veba();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Düşüş"))
        {
            phl.Dusus();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Böyle Buyurdu Zerdüşt"))
        {
            phl.Zerdust();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Putların Alacakaranlığı"))
        {
            phl.Putlar();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("İyinin ve Kötünün Ötesinde"))
        {
            phl.IyininOtesi();
            JOptionPane.showMessageDialog(rootPane,"Name : "+phl.bookName+"\n"+"Writer : "+phl.writer+"\n"+
            "Type : "+phl.type+"\n"+"Page Number : "+phl.pageNumber+"\n"+"Price : "+phl.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Homo Deus : Yarının Kısa Bir Tarihi"))
        {
            res.HomoDeus();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("21. Yüzyıl için 21 Ders"))
        {
            res.Yuzyil();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Hayvanlardan Tanrılara Sapiens"))
        {
            res.Sapiens();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Gazi Mustafa Kemal Atatürk"))
        {
            res.GaziAtaturk();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Türklerin Altın Çağı"))
        {
            res.TurklerinAltinCagi();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("İstanbul'dan Sayfalar"))
        {
            res.Istanbul();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Rönesans Avrupası"))
        {
            res.Ronesans();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Devlet-i Aliyye-Osmanlı İmparatorluğu"))
        {
            res.DevletiAliyye();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Fatih Sultan Mehemmed Han"))
        {
            res.FatihSultan();
            JOptionPane.showMessageDialog(rootPane,"Name : "+res.bookName+"\n"+"Writer : "+res.writer+"\n"+
            "Type : "+res.type+"\n"+"Page Number : "+res.pageNumber+"\n"+"Price : "+res.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Her Şeyin Anlamı"))
        {
            scn.HerSey();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Feynman Fizik Dersleri"))
        {
            scn.Feynman();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Altı Zor Parça"))
        {
            scn.ZorParca();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Zamanın Kısa Tarihi"))
        {
            scn.Zaman();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Karadelikler"))
        {
            scn.Karadelikler();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Büyük Sorulara Kısa Yanıtlar"))
        {
            scn.BuyukSoru();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Hiper Uzay"))
        {
            scn.HiperUzay();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("Paralel Dünyalar"))
        {
            scn.Paralel();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals("İnsanlığın Geleceği"))
        {
            scn.Insanlik();
            JOptionPane.showMessageDialog(rootPane,"Name : "+scn.bookName+"\n"+"Writer : "+scn.writer+"\n"+
            "Type : "+scn.type+"\n"+"Page Number : "+scn.pageNumber+"\n"+"Price : "+scn.price+" TL");
        }
        if(jList2.getSelectedValue().equals(null)){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jList3.setModel(model); 
        model.addElement(jList2.getSelectedValue());
        
        if(jList2.getSelectedValue().equals("Suç ve Ceza"))
        {
            ltr.SucVeCeza();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Karamazov Kardeşler"))
        {
            ltr.KaramozovKardesler();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Yeraltından Notlar"))
        {
            ltr.YerAltindanNotlar();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Dönüşüm"))
        {
            ltr.Donusum();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Aforizmalar"))
        {
            ltr.Aforizmalar();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        
        if(jList2.getSelectedValue().equals("Dava"))
        {
            ltr.Dava();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Serenad"))
        {
            ltr.Serenad();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Huzursuzluk"))
        {
            ltr.Huzursuzluk();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Kardeşimin Hikayesi"))
        {
            ltr.KardesiminHikayesi();
            c.Sum(ltr.price);
            list.add(ltr.bookName+"   "+ltr.price);
        }
        if(jList2.getSelectedValue().equals("Venedik Taciri"))
        {
            art.VenedikTaciri();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Romeo ve Juliet"))
        {
            art.RomeoJuliet();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Hamlet"))
        {
            art.Hamlet();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Velázquez"))
        {
            art.Velazquez();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Raffaello"))
        {
            art.Raffaello();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Monet"))
        {
            art.Monet();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Antigone"))
        {
            art.Antigone();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Kral Oidipus"))
        {
            art.Oidipus();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Elektra"))
        {
            art.Elektra();
            c.Sum(art.price);
            list.add(art.bookName+"   "+art.price);
        }
        if(jList2.getSelectedValue().equals("Devlet"))
        {
            phl.Devlet();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Sokrates'in Savunması"))
        {
            phl.Sokrates();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Sofist"))
        {
            phl.Sofist();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Yabancı"))
        {
            phl.Yabancı();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Veba"))
        {
            phl.Veba();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Düşüş"))
        {
            phl.Dusus();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Böyle Buyurdu Zerdüşt"))
        {
            phl.Zerdust();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Putların Alacakaranlığı"))
        {
            phl.Putlar();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("İyinin ve Kötünün Ötesinde"))
        {
            phl.IyininOtesi();
            c.Sum(phl.price);
            list.add(phl.bookName+"   "+phl.price);
        }
        if(jList2.getSelectedValue().equals("Homo Deus : Yarının Kısa Bir Tarihi"))
        {
            res.HomoDeus();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("21. Yüzyıl için 21 Ders"))
        {
            res.Yuzyil();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Hayvanlardan Tanrılara Sapiens"))
        {
            res.Sapiens();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Gazi Mustafa Kemal Atatürk"))
        {
            res.GaziAtaturk();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Türklerin Altın Çağı"))
        {
            res.TurklerinAltinCagi();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("İstanbul'dan Sayfalar"))
        {
            res.Istanbul();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Rönesans Avrupası"))
        {
            res.Ronesans();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Devlet-i Aliyye-Osmanlı İmparatorluğu"))
        {
            res.DevletiAliyye();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Fatih Sultan Mehemmed Han"))
        {
            res.FatihSultan();
            c.Sum(res.price);
            list.add(res.bookName+"   "+res.price);
        }
        if(jList2.getSelectedValue().equals("Her Şeyin Anlamı"))
        {
            scn.HerSey();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Feynman Fizik Dersleri"))
        {
            scn.Feynman();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Altı Zor Parça"))
        {
            scn.ZorParca();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Zamanın Kısa Tarihi"))
        {
            scn.Zaman();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Karadelikler"))
        {
            scn.Karadelikler();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Büyük Sorulara Kısa Yanıtlar"))
        {
            scn.BuyukSoru();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Hiper Uzay"))
        {
            scn.HiperUzay();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("Paralel Dünyalar"))
        {
            scn.Paralel();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals("İnsanlığın Geleceği"))
        {
            scn.Insanlik();
            c.Sum(scn.price);
            list.add(scn.bookName+"   "+scn.price);
        }
        if(jList2.getSelectedValue().equals(null)){
            
        }
        String number=formatter.format(c.Total);
        jLabel5.setText("Total Price :"+number);
        Total=c.Total;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(jList3.getSelectedValue().equals("Suç ve Ceza"))
        {
            ltr.SucVeCeza();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Karamazov Kardeşler"))
        {
            ltr.KaramozovKardesler();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Yeraltından Notlar"))
        {
            ltr.YerAltindanNotlar();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Dönüşüm"))
        {
            ltr.Donusum();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Aforizmalar"))
        {
            ltr.Aforizmalar();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Dava"))
        {
            ltr.Dava();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Serenad"))
        {
            ltr.Serenad();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Huzursuzluk"))
        {
            ltr.Huzursuzluk();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Kardeşimin Hikayesi"))
        {
            ltr.KardesiminHikayesi();
            c.Extract(ltr.price,Total);
        }
        if(jList3.getSelectedValue().equals("Venedik Taciri"))
        {
            art.VenedikTaciri();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Romeo ve Juliet"))
        {
            art.RomeoJuliet();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Hamlet"))
        {
            art.Hamlet();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Velázquez"))
        {
            art.Velazquez();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Raffaello"))
        {
            art.Raffaello();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Monet"))
        {
            art.Monet();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Antigone"))
        {
            art.Antigone();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Kral Oidipus"))
        {
            art.Oidipus();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Elektra"))
        {
            art.Elektra();
            c.Extract(art.price,Total);
        }
        if(jList3.getSelectedValue().equals("Devlet"))
        {
            phl.Devlet();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Sokrates'in Savunması"))
        {
            phl.Sokrates();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Sofist"))
        {
            phl.Sofist();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Yabancı"))
        {
            phl.Yabancı();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Veba"))
        {
            phl.Veba();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Düşüş"))
        {
            phl.Dusus();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Böyle Buyurdu Zerdüşt"))
        {
            phl.Zerdust();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Putların Alacakaranlığı"))
        {
            phl.Putlar();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("İyinin ve Kötünün Ötesinde"))
        {
            phl.IyininOtesi();
            c.Extract(phl.price,Total);
        }
        if(jList3.getSelectedValue().equals("Homo Deus : Yarının Kısa Bir Tarihi"))
        {
            res.HomoDeus();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("21. Yüzyıl için 21 Ders"))
        {
            res.Yuzyil();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Hayvanlardan Tanrılara Sapiens"))
        {
            res.Sapiens();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Gazi Mustafa Kemal Atatürk"))
        {
            res.GaziAtaturk();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Türklerin Altın Çağı"))
        {
            res.TurklerinAltinCagi();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("İstanbul'dan Sayfalar"))
        {
            res.Istanbul();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Rönesans Avrupası"))
        {
            res.Ronesans();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Devlet-i Aliyye-Osmanlı İmparatorluğu"))
        {
            res.DevletiAliyye();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Fatih Sultan Mehemmed Han"))
        {
            res.FatihSultan();
            c.Extract(res.price,Total);
        }
        if(jList3.getSelectedValue().equals("Her Şeyin Anlamı"))
        {
            scn.HerSey();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Feynman Fizik Dersleri"))
        {
            scn.Feynman();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Altı Zor Parça"))
        {
            scn.ZorParca();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Zamanın Kısa Tarihi"))
        {
            scn.Zaman();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Karadelikler"))
        {
            scn.Karadelikler();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Büyük Sorulara Kısa Yanıtlar"))
        {
            scn.BuyukSoru();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Hiper Uzay"))
        {
            scn.HiperUzay();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("Paralel Dünyalar"))
        {
            scn.Paralel();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals("İnsanlığın Geleceği"))
        {
            scn.Insanlik();
            c.Extract(scn.price,Total);
        }
        if(jList3.getSelectedValue().equals(null)){
            
        }
        String number=formatter.format(c.Total);
        jLabel5.setText("Total Price :"+number);
        
        model.remove(jList3.getSelectedIndex());
        list.remove(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String number=formatter.format(c.Total);
        list.add(String.valueOf(number));
        Print pr=new Print();
        try {
            pr.Print(list);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    DecimalFormat formatter = new DecimalFormat("##.###");
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
